// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9yDFyV7uO48th6HYfPHMYAx78DoBAC2M',
    appId: '1:59246328547:web:41b237998a852ecf40a3d6',
    messagingSenderId: '59246328547',
    projectId: 'hamaro-gunaso-1bb7c',
    authDomain: 'hamaro-gunaso-1bb7c.firebaseapp.com',
    databaseURL: 'https://hamaro-gunaso-1bb7c-default-rtdb.firebaseio.com',
    storageBucket: 'hamaro-gunaso-1bb7c.firebasestorage.app',
    measurementId: 'G-CCRKS4J8P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjIToegYfw-syhtx8Dzj2qwdYu_P1RMyg',
    appId: '1:59246328547:android:dc2cb3b0640d535e40a3d6',
    messagingSenderId: '59246328547',
    projectId: 'hamaro-gunaso-1bb7c',
    databaseURL: 'https://hamaro-gunaso-1bb7c-default-rtdb.firebaseio.com',
    storageBucket: 'hamaro-gunaso-1bb7c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9yDFyV7uO48th6HYfPHMYAx78DoBAC2M',
    appId: '1:59246328547:web:e973b4acb22a612e40a3d6',
    messagingSenderId: '59246328547',
    projectId: 'hamaro-gunaso-1bb7c',
    authDomain: 'hamaro-gunaso-1bb7c.firebaseapp.com',
    databaseURL: 'https://hamaro-gunaso-1bb7c-default-rtdb.firebaseio.com',
    storageBucket: 'hamaro-gunaso-1bb7c.firebasestorage.app',
    measurementId: 'G-BWFHL8RJFQ',
  );
}
